python phase_fl_test.py --model_index 0
python phase_fl_test.py --model_index 1
python phase_fl_test.py --model_index 2
python phase_fl_test.py --model_index 3
python phase_fl_test.py --model_index 4
python phase_fl_test.py --model_index 5
python phase_fl_test.py --model_index 6
python phase_fl_test.py --model_index 7
python phase_fl_test.py --model_index 8